CREATE TABLE PUNISHMENT_ACTIVE (
    GUILD_ID NUMBER,
    PUNISHMENT_ID NUMBER,
    PUNISHMENT_TIER NUMBER,
    USER_ID NUMBER,
    START_DATE DATE,
    DURATION_IN_MS NUMBER,
    CONSTRAINT UNIQUE_ACTIVE_PUNISHMENT UNIQUE (GUILD_ID, PUNISHMENT_ID, USER_ID),
    CONSTRAINT PUNISHMENT_ACTIVE_FK FOREIGN KEY (GUILD_ID, PUNISHMENT_ID)
        REFERENCES PUNISHMENT(GUILD_ID, PUNISHMENT_ID) ON DELETE CASCADE
);
