CREATE TABLE PUNISHMENT_TIER (
    GUILD_ID NUMBER,
    PUNISHMENT_ID NUMBER,
    PUNISHMENT_TIER NUMBER,
    PUNISHMENT_TYPE VARCHAR2(10 BYTE),
    PUNISHMENT_TIME NUMBER,
    CONSTRAINT PUNISHMENT_TIER_PK PRIMARY KEY (GUILD_ID, PUNISHMENT_ID, PUNISHMENT_TIER),
    CONSTRAINT PUNISHMENT_TIER_PUNISHMENT_FK FOREIGN KEY (GUILD_ID, PUNISHMENT_ID)
        REFERENCES PUNISHMENT(GUILD_ID, PUNISHMENT_ID) ON DELETE CASCADE
);
