CREATE TABLE PUNISHMENT (
    GUILD_ID NUMBER,
    PUNISHMENT_ID NUMBER,
    NAME VARCHAR2(25 BYTE),
    CREATE_USER NUMBER,
    CREATE_STAMP DATE DEFAULT sysdate,
    CONSTRAINT PUNISHMENT_PK PRIMARY KEY (GUILD_ID, PUNISHMENT_ID),
    CONSTRAINT UNIQUE_PUNISHMENT_NAME_PER_GUILD UNIQUE (GUILD_ID, NAME),
    CONSTRAINT PUNISHMENT_SETTING_FK FOREIGN KEY (GUILD_ID) REFERENCES SETTING(GUILD_ID)
);
