CREATE TABLE PUNISHMENT_LOGS (
    GUILD_ID NUMBER,
    PUNISHMENT_LOG_ID NUMBER,
    STAFF_ID NUMBER,
    USER_ID NUMBER,
    PUNISHMENT_TYPE VARCHAR2(10 BYTE),
    DURATION VARCHAR2(200 BYTE),
    REASON VARCHAR2(200 BYTE),
    IS_ARCHIVED NUMBER DEFAULT 0,
    CREATE_STAMP DATE DEFAULT sysdate,
    IS_SERVED NUMBER DEFAULT 0,
    CONSTRAINT PUNISHMENT_LOG_PK PRIMARY KEY (GUILD_ID, PUNISHMENT_LOG_ID),
    CONSTRAINT PUNISHMENT_LOG_SETTING_FK FOREIGN KEY (GUILD_ID) REFERENCES SETTING(GUILD_ID)
);
