CREATE TABLE SETTING (
    GUILD_ID NUMBER,
    PREFIX VARCHAR2(20 BYTE) DEFAULT 's!',
    MUTE_ROLE_ID NUMBER,
    PUNISHMENT_LOG_ID NUMBER,
    PUNISHMENT_RESET NUMBER DEFAULT 86400000,
    CONSTRAINT SETTING_PK PRIMARY KEY (GUILD_ID)
);
