CREATE TABLE UNIT_CMD (
    GUILD_ID NUMBER,
    UNIT_ID NUMBER,
    CMD_ID NUMBER,
    CONSTRAINT UNIT_CMD_PK PRIMARY KEY (GUILD_ID, CMD_ID),
    CONSTRAINT UNIT_CMD_CMD_FK FOREIGN KEY (GUILD_ID, CMD_ID) REFERENCES COMMAND(GUILD_ID, CMD_ID),
    CONSTRAINT UNIT_CMD_UNIT_FK FOREIGN KEY (GUILD_ID, UNIT_ID) REFERENCES UNIT(GUILD_ID, UNIT_ID) ON DELETE CASCADE
);
