CREATE TABLE UNIT_ROLE (
    GUILD_ID NUMBER,
    UNIT_ID NUMBER,
    DISCORD_ROLE_ID NUMBER,
    CONSTRAINT UNIT_ROLE_UNIT_FK FOREIGN KEY (GUILD_ID, UNIT_ID)
        REFERENCES UNIT(GUILD_ID, UNIT_ID) ON DELETE CASCADE
);

CREATE INDEX UNIT_ROLE_IDX ON UNIT_ROLE (GUILD_ID, UNIT_ID, DISCORD_ROLE_ID);
