CREATE TABLE UNIT (
    GUILD_ID NUMBER,
    UNIT_ID NUMBER,
    UNIT_NAME VARCHAR2(25 BYTE),
    CONSTRAINT GROUP_PK PRIMARY KEY (GUILD_ID, UNIT_ID),
    CONSTRAINT UNIQUE_GUILD_GROUP_NAME UNIQUE (GUILD_ID, UNIT_NAME),
    CONSTRAINT GROUP_SETTING_FK FOREIGN KEY (GUILD_ID) REFERENCES SETTING(GUILD_ID)
);
